#pragma once
#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <numeric>
#include <sstream>
#include <algorithm>
#include <fstream>

using std::cout;
using std::cin;
using std::setprecision;
using std::setw;
using std::left;
using std::right;
using std::endl;
using std::accumulate;
using std::nth_element;
using std::stringstream;
using std::istream;
using std::ostream;
using std::string;
using std::vector;